bugzilla-creds:
    user: ''
    password: ''
    domain: ''
    bugzilla-url: ''
telegram-creds:
    token: ''
default-params:
    default_product: ''
    default_component: ''
db-params:
    MONGODB_URI: ''